// AUTO-GENERATED by scripts/generateCategoryTranslations.js
// Languages: ar, en, fr, de, es, tr, ru, fa
// Regenerate: node backend/scripts/generateCategoryTranslations.js
// Or POST /api/ads/admin/regenerate-translations with x-admin-key header
// When adding new categories, run: node backend/scripts/generateCategoryTranslations.js

const CATEGORY_TRANSLATIONS = {
  "cat_electronics": {
    "ar": "إلكترونيات",
    "en": "Electronics",
    "fr": "Électronique",
    "de": "Elektronik",
    "es": "Electrónica",
    "tr": "Elektronik",
    "ru": "Электроника",
    "fa": "الکترونیک"
  },
  "cat_cars": {
    "ar": "سيارات ومركبات",
    "en": "Cars & Vehicles",
    "fr": "Voitures & Véhicules",
    "de": "Autos & Fahrzeuge",
    "es": "Coches & Vehículos",
    "tr": "Arabalar & Araçlar",
    "ru": "Авто & Транспорт",
    "fa": "خودرو و وسایل نقلیه"
  },
  "cat_real_estate": {
    "ar": "عقارات",
    "en": "Real Estate",
    "fr": "Immobilier",
    "de": "Immobilien",
    "es": "Inmuebles",
    "tr": "Emlak",
    "ru": "Недвижимость",
    "fa": "املاک"
  },
  "cat_fashion": {
    "ar": "أزياء وملابس",
    "en": "Fashion & Clothing",
    "fr": "Mode & Vêtements",
    "de": "Mode & Kleidung",
    "es": "Moda & Ropa",
    "tr": "Moda & Giyim",
    "ru": "Мода & Одежда",
    "fa": "مد و لباس"
  },
  "cat_furniture": {
    "ar": "أثاث ومنزل",
    "en": "Furniture & Home",
    "fr": "Meubles & Maison",
    "de": "Möbel & Haus",
    "es": "Muebles & Hogar",
    "tr": "Mobilya & Ev",
    "ru": "Мебель & Дом",
    "fa": "مبل و خانه"
  },
  "cat_services": {
    "ar": "خدمات",
    "en": "Services",
    "fr": "Services",
    "de": "Dienstleistungen",
    "es": "Servicios",
    "tr": "Hizmetler",
    "ru": "Услуги",
    "fa": "خدمات"
  },
  "cat_jobs": {
    "ar": "وظائف",
    "en": "Jobs",
    "fr": "Emplois",
    "de": "Jobs",
    "es": "Empleos",
    "tr": "İş İlanları",
    "ru": "Работа",
    "fa": "مشاغل"
  },
  "cat_pets": {
    "ar": "حيوانات أليفة",
    "en": "Pets",
    "fr": "Animaux",
    "de": "Haustiere",
    "es": "Mascotas",
    "tr": "Evcil Hayvanlar",
    "ru": "Домашние животные",
    "fa": "حیوانات خانگی"
  },
  "cat_sports": {
    "ar": "رياضة وترفيه",
    "en": "Sports & Leisure",
    "fr": "Sport & Loisirs",
    "de": "Sport & Freizeit",
    "es": "Deporte & Ocio",
    "tr": "Spor & Eğlence",
    "ru": "Спорт & Отдых",
    "fa": "ورزش و تفریح"
  },
  "cat_kids": {
    "ar": "أطفال ومستلزماتهم",
    "en": "Kids & Baby",
    "fr": "Enfants & Bébé",
    "de": "Kinder & Baby",
    "es": "Niños & Bebé",
    "tr": "Çocuk & Bebek",
    "ru": "Дети & Малыши",
    "fa": "کودک و نوزاد"
  },
  "cat_hobbies": {
    "ar": "هوايات وترفيه",
    "en": "Hobbies",
    "fr": "Loisirs & Hobbies",
    "de": "Hobbys",
    "es": "Aficiones",
    "tr": "Hobiler",
    "ru": "Хобби",
    "fa": "سرگرمی‌ها"
  },
  "cat_agriculture": {
    "ar": "زراعة ومواشي",
    "en": "Agriculture & Livestock",
    "fr": "Agriculture & Élevage",
    "de": "Landwirtschaft & Vieh",
    "es": "Agricultura & Ganadería",
    "tr": "Tarım & Hayvancılık",
    "ru": "Сельское хозяйство",
    "fa": "کشاورزی و دام"
  },
  "cat_food": {
    "ar": "أكل وشرب",
    "en": "Food & Drinks",
    "fr": "Alimentation & Boissons",
    "de": "Essen & Trinken",
    "es": "Comida & Bebidas",
    "tr": "Yiyecek & İçecek",
    "ru": "Еда & Напитки",
    "fa": "خوراک و نوشیدنی"
  },
  "cat_tools": {
    "ar": "أدوات ومعدات",
    "en": "Tools & Equipment",
    "fr": "Outils & Équipements",
    "de": "Werkzeuge & Geräte",
    "es": "Herramientas & Equipos",
    "tr": "Aletler & Ekipmanlar",
    "ru": "Инструменты & Оборудование",
    "fa": "ابزار و تجهیزات"
  },
  "cat_general": {
    "ar": "متفرقات",
    "en": "General",
    "fr": "Divers",
    "de": "Allgemein",
    "es": "General",
    "tr": "Genel",
    "ru": "Разное",
    "fa": "متفرقه"
  },
  "sub_electronics_mobile": {
    "ar": "موبايلات وهواتف",
    "en": "Mobile Phones",
    "fr": "Téléphones Mobiles",
    "de": "Handys",
    "es": "Teléfonos Móviles",
    "tr": "Cep Telefonları",
    "ru": "Мобильные телефоны",
    "fa": "موبایل و گوشی"
  },
  "sub_electronics_laptop": {
    "ar": "لابتوب وكمبيوتر",
    "en": "Laptops & PCs",
    "fr": "Ordinateurs Portables",
    "de": "Laptops & PCs",
    "es": "Portátiles & PCs",
    "tr": "Dizüstü & Masaüstü",
    "ru": "Ноутбуки & ПК",
    "fa": "لپ‌تاپ و کامپیوتر"
  },
  "sub_electronics_tablet": {
    "ar": "تابلت",
    "en": "Tablets",
    "fr": "Tablettes",
    "de": "Tablets",
    "es": "Tabletas",
    "tr": "Tabletler",
    "ru": "Планшеты",
    "fa": "تبلت"
  },
  "sub_electronics_camera": {
    "ar": "كاميرات",
    "en": "Cameras",
    "fr": "Appareils Photo",
    "de": "Kameras",
    "es": "Cámaras",
    "tr": "Kameralar",
    "ru": "Камеры",
    "fa": "دوربین"
  },
  "sub_electronics_tv": {
    "ar": "تلفزيونات وشاشات",
    "en": "TVs & Screens",
    "fr": "Téléviseurs & Écrans",
    "de": "Fernseher & Bildschirme",
    "es": "Televisores & Pantallas",
    "tr": "TV & Ekranlar",
    "ru": "Телевизоры & Экраны",
    "fa": "تلویزیون و مانیتور"
  },
  "sub_electronics_gaming": {
    "ar": "ألعاب فيديو",
    "en": "Gaming",
    "fr": "Jeux Vidéo",
    "de": "Gaming",
    "es": "Videojuegos",
    "tr": "Oyun",
    "ru": "Игры",
    "fa": "بازی ویدیویی"
  },
  "sub_electronics_accessories_tech": {
    "ar": "إكسسوارات تقنية",
    "en": "Tech Accessories",
    "fr": "Accessoires Tech",
    "de": "Technik-Zubehör",
    "es": "Accesorios Tecnológicos",
    "tr": "Teknoloji Aksesuarları",
    "ru": "Техаксессуары",
    "fa": "لوازم جانبی فناوری"
  },
  "sub_electronics_audio": {
    "ar": "صوتيات وسماعات",
    "en": "Audio",
    "fr": "Audio & Son",
    "de": "Audio & Lautsprecher",
    "es": "Audio & Sonido",
    "tr": "Ses Sistemleri",
    "ru": "Аудио & Звук",
    "fa": "صوت و هدفون"
  },
  "sub_cars_passenger_car": {
    "ar": "سيارات ملاكي",
    "en": "Passenger Cars",
    "fr": "Voitures de Tourisme",
    "de": "Personenwagen",
    "es": "Coches Particulares",
    "tr": "Binek Araçlar",
    "ru": "Легковые автомобили",
    "fa": "خودروی سواری"
  },
  "sub_cars_commercial_vehicle": {
    "ar": "سيارات نقل وتجارية",
    "en": "Commercial Vehicles",
    "fr": "Véhicules Commerciaux",
    "de": "Nutzfahrzeuge",
    "es": "Vehículos Comerciales",
    "tr": "Ticari Araçlar",
    "ru": "Коммерческий транспорт",
    "fa": "وسایل نقلیه تجاری"
  },
  "sub_cars_motorcycle": {
    "ar": "موتوسيكلات",
    "en": "Motorcycles",
    "fr": "Motos",
    "de": "Motorräder",
    "es": "Motos",
    "tr": "Motosikletler",
    "ru": "Мотоциклы",
    "fa": "موتورسیکلت"
  },
  "sub_cars_car_parts": {
    "ar": "قطع غيار",
    "en": "Spare Parts",
    "fr": "Pièces Détachées",
    "de": "Ersatzteile",
    "es": "Repuestos",
    "tr": "Yedek Parçalar",
    "ru": "Запчасти",
    "fa": "قطعات یدکی"
  },
  "sub_cars_car_accessories": {
    "ar": "إكسسوارات سيارات",
    "en": "Car Accessories",
    "fr": "Accessoires Auto",
    "de": "Auto-Zubehör",
    "es": "Accesorios de Coche",
    "tr": "Araba Aksesuarları",
    "ru": "Автоаксессуары",
    "fa": "لوازم جانبی خودرو"
  },
  "sub_cars_boats": {
    "ar": "قوارب ومراكب",
    "en": "Boats",
    "fr": "Bateaux",
    "de": "Boote",
    "es": "Barcos",
    "tr": "Tekneler",
    "ru": "Лодки",
    "fa": "قایق"
  },
  "sub_real_estate_apartment_rent": {
    "ar": "شقق للإيجار",
    "en": "Apartments for Rent",
    "fr": "Appartements à Louer",
    "de": "Wohnungen zur Miete",
    "es": "Pisos en Alquiler",
    "tr": "Kiralık Daireler",
    "ru": "Квартиры в аренду",
    "fa": "آپارتمان اجاره‌ای"
  },
  "sub_real_estate_apartment_sale": {
    "ar": "شقق للبيع",
    "en": "Apartments for Sale",
    "fr": "Appartements à Vendre",
    "de": "Wohnungen zu kaufen",
    "es": "Pisos en Venta",
    "tr": "Satılık Daireler",
    "ru": "Квартиры на продажу",
    "fa": "آپارتمان فروشی"
  },
  "sub_real_estate_villa": {
    "ar": "فيلات ومنازل",
    "en": "Villas & Houses",
    "fr": "Villas & Maisons",
    "de": "Villen & Häuser",
    "es": "Villas & Casas",
    "tr": "Villalar & Evler",
    "ru": "Виллы & Дома",
    "fa": "ویلا و خانه"
  },
  "sub_real_estate_land": {
    "ar": "أراضي",
    "en": "Land",
    "fr": "Terrains",
    "de": "Grundstücke",
    "es": "Terrenos",
    "tr": "Arazi",
    "ru": "Земельные участки",
    "fa": "زمین"
  },
  "sub_real_estate_commercial_space": {
    "ar": "محلات ومكاتب",
    "en": "Commercial Spaces",
    "fr": "Locaux Commerciaux",
    "de": "Gewerberäume",
    "es": "Locales Comerciales",
    "tr": "Ticari Alanlar",
    "ru": "Коммерческая недвижимость",
    "fa": "فضای تجاری"
  },
  "sub_real_estate_room_rent": {
    "ar": "غرف للإيجار",
    "en": "Rooms for Rent",
    "fr": "Chambres à Louer",
    "de": "Zimmer zur Miete",
    "es": "Habitaciones en Alquiler",
    "tr": "Kiralık Odalar",
    "ru": "Комнаты в аренду",
    "fa": "اتاق اجاره‌ای"
  },
  "sub_fashion_mens_clothing": {
    "ar": "ملابس رجالي",
    "en": "Men's Clothing",
    "fr": "Vêtements Hommes",
    "de": "Herrenkleidung",
    "es": "Ropa de Hombre",
    "tr": "Erkek Giyim",
    "ru": "Мужская одежда",
    "fa": "لباس مردانه"
  },
  "sub_fashion_womens_clothing": {
    "ar": "ملابس حريمي",
    "en": "Women's Clothing",
    "fr": "Vêtements Femmes",
    "de": "Damenkleidung",
    "es": "Ropa de Mujer",
    "tr": "Kadın Giyim",
    "ru": "Женская одежда",
    "fa": "لباس زنانه"
  },
  "sub_fashion_kids_clothing": {
    "ar": "ملابس أطفال",
    "en": "Kids' Clothing",
    "fr": "Vêtements Enfants",
    "de": "Kinderkleidung",
    "es": "Ropa de Niños",
    "tr": "Çocuk Giyim",
    "ru": "Детская одежда",
    "fa": "لباس کودک"
  },
  "sub_fashion_shoes": {
    "ar": "أحذية",
    "en": "Shoes",
    "fr": "Chaussures",
    "de": "Schuhe",
    "es": "Zapatos",
    "tr": "Ayakkabılar",
    "ru": "Обувь",
    "fa": "کفش"
  },
  "sub_fashion_bags": {
    "ar": "شنط وحقائب",
    "en": "Bags",
    "fr": "Sacs",
    "de": "Taschen",
    "es": "Bolsos",
    "tr": "Çantalar",
    "ru": "Сумки",
    "fa": "کیف"
  },
  "sub_fashion_watches_jewelry": {
    "ar": "ساعات ومجوهرات",
    "en": "Watches & Jewelry",
    "fr": "Montres & Bijoux",
    "de": "Uhren & Schmuck",
    "es": "Relojes & Joyas",
    "tr": "Saatler & Mücevherler",
    "ru": "Часы & Ювелирные изделия",
    "fa": "ساعت و جواهرات"
  },
  "sub_fashion_accessories_fashion": {
    "ar": "إكسسوارات",
    "en": "Accessories",
    "fr": "Accessoires",
    "de": "Accessoires",
    "es": "Accesorios",
    "tr": "Aksesuarlar",
    "ru": "Аксессуары",
    "fa": "اکسسوری"
  },
  "sub_furniture_living_room": {
    "ar": "أثاث صالون وريسبشن",
    "en": "Living Room Furniture",
    "fr": "Meubles Salon",
    "de": "Wohnzimmermöbel",
    "es": "Muebles de Sala",
    "tr": "Oturma Odası Mobilyaları",
    "ru": "Мебель гостиной",
    "fa": "مبل و پذیرایی"
  },
  "sub_furniture_bedroom": {
    "ar": "أثاث غرف نوم",
    "en": "Bedroom Furniture",
    "fr": "Meubles Chambre",
    "de": "Schlafzimmermöbel",
    "es": "Muebles de Dormitorio",
    "tr": "Yatak Odası Mobilyaları",
    "ru": "Мебель спальни",
    "fa": "مبل اتاق خواب"
  },
  "sub_furniture_kitchen_appliances": {
    "ar": "أجهزة مطبخ",
    "en": "Kitchen Appliances",
    "fr": "Électroménager Cuisine",
    "de": "Küchengeräte",
    "es": "Electrodomésticos de Cocina",
    "tr": "Mutfak Aletleri",
    "ru": "Кухонная техника",
    "fa": "لوازم آشپزخانه"
  },
  "sub_furniture_home_appliances": {
    "ar": "أجهزة منزلية كبيرة",
    "en": "Large Home Appliances",
    "fr": "Gros Électroménager",
    "de": "Große Haushaltsgeräte",
    "es": "Grandes Electrodomésticos",
    "tr": "Büyük Ev Aletleri",
    "ru": "Крупная бытовая техника",
    "fa": "لوازم خانگی بزرگ"
  },
  "sub_furniture_decor": {
    "ar": "ديكور وإضاءة",
    "en": "Decor & Lighting",
    "fr": "Décoration & Éclairage",
    "de": "Dekor & Beleuchtung",
    "es": "Decoración & Iluminación",
    "tr": "Dekorasyon & Aydınlatma",
    "ru": "Декор & Освещение",
    "fa": "دکوراسیون و روشنایی"
  },
  "sub_furniture_ac_heating": {
    "ar": "تكييف وتدفئة",
    "en": "AC & Heating",
    "fr": "Climatisation & Chauffage",
    "de": "Klimaanlage & Heizung",
    "es": "Aire Acondicionado & Calefacción",
    "tr": "Klima & Isıtma",
    "ru": "Кондиционер & Отопление",
    "fa": "تهویه و گرمایش"
  },
  "sub_services_education": {
    "ar": "تعليم ودروس",
    "en": "Education & Tutoring",
    "fr": "Éducation & Cours",
    "de": "Bildung & Nachhilfe",
    "es": "Educación & Clases",
    "tr": "Eğitim & Dersler",
    "ru": "Образование & Репетиторство",
    "fa": "آموزش و تدریس"
  },
  "sub_services_repair_maintenance": {
    "ar": "صيانة وإصلاح",
    "en": "Repair & Maintenance",
    "fr": "Réparation & Maintenance",
    "de": "Reparatur & Wartung",
    "es": "Reparación & Mantenimiento",
    "tr": "Tamir & Bakım",
    "ru": "Ремонт & Обслуживание",
    "fa": "تعمیر و نگهداری"
  },
  "sub_services_design_tech": {
    "ar": "تصميم وبرمجة",
    "en": "Design & Programming",
    "fr": "Design & Programmation",
    "de": "Design & Programmierung",
    "es": "Diseño & Programación",
    "tr": "Tasarım & Programlama",
    "ru": "Дизайн & Программирование",
    "fa": "طراحی و برنامه‌نویسی"
  },
  "sub_services_transport": {
    "ar": "نقل وشحن",
    "en": "Transport & Shipping",
    "fr": "Transport & Livraison",
    "de": "Transport & Versand",
    "es": "Transporte & Envío",
    "tr": "Nakliye & Kargo",
    "ru": "Транспорт & Доставка",
    "fa": "حمل و نقل"
  },
  "sub_services_health_beauty": {
    "ar": "صحة وجمال",
    "en": "Health & Beauty",
    "fr": "Santé & Beauté",
    "de": "Gesundheit & Schönheit",
    "es": "Salud & Belleza",
    "tr": "Sağlık & Güzellik",
    "ru": "Здоровье & Красота",
    "fa": "سلامت و زیبایی"
  },
  "sub_services_cleaning": {
    "ar": "تنظيف ونظافة",
    "en": "Cleaning",
    "fr": "Nettoyage",
    "de": "Reinigung",
    "es": "Limpieza",
    "tr": "Temizlik",
    "ru": "Уборка",
    "fa": "نظافت"
  },
  "sub_services_legal_financial": {
    "ar": "قانوني ومالي",
    "en": "Legal & Financial",
    "fr": "Juridique & Financier",
    "de": "Rechts- & Finanzdienstleistungen",
    "es": "Legal & Financiero",
    "tr": "Hukuki & Mali",
    "ru": "Юридические & Финансовые",
    "fa": "حقوقی و مالی"
  },
  "sub_services_events": {
    "ar": "مناسبات وأفراح",
    "en": "Events & Weddings",
    "fr": "Événements & Mariages",
    "de": "Events & Hochzeiten",
    "es": "Eventos & Bodas",
    "tr": "Etkinlikler & Düğünler",
    "ru": "Мероприятия & Свадьбы",
    "fa": "مراسم و جشن"
  },
  "sub_jobs_job_offered": {
    "ar": "وظائف متاحة",
    "en": "Jobs Available",
    "fr": "Offres d'Emploi",
    "de": "Stellenangebote",
    "es": "Ofertas de Empleo",
    "tr": "İş İlanları",
    "ru": "Вакансии",
    "fa": "آگهی استخدام"
  },
  "sub_jobs_job_wanted": {
    "ar": "باحثون عن عمل",
    "en": "Job Seekers",
    "fr": "Recherche d'Emploi",
    "de": "Jobsuche",
    "es": "Búsqueda de Empleo",
    "tr": "İş Arayanlar",
    "ru": "Ищу работу",
    "fa": "جویای کار"
  },
  "sub_jobs_freelance": {
    "ar": "فريلانس وعمل حر",
    "en": "Freelance",
    "fr": "Freelance",
    "de": "Freiberuflich",
    "es": "Freelance",
    "tr": "Serbest Çalışma",
    "ru": "Фриланс",
    "fa": "فریلنسر"
  },
  "sub_pets_cats": {
    "ar": "قطط",
    "en": "Cats",
    "fr": "Chats",
    "de": "Katzen",
    "es": "Gatos",
    "tr": "Kediler",
    "ru": "Кошки",
    "fa": "گربه"
  },
  "sub_pets_dogs": {
    "ar": "كلاب",
    "en": "Dogs",
    "fr": "Chiens",
    "de": "Hunde",
    "es": "Perros",
    "tr": "Köpekler",
    "ru": "Собаки",
    "fa": "سگ"
  },
  "sub_pets_birds": {
    "ar": "طيور",
    "en": "Birds",
    "fr": "Oiseaux",
    "de": "Vögel",
    "es": "Pájaros",
    "tr": "Kuşlar",
    "ru": "Птицы",
    "fa": "پرنده"
  },
  "sub_pets_fish": {
    "ar": "أسماك وأحواض",
    "en": "Fish & Aquariums",
    "fr": "Poissons & Aquariums",
    "de": "Fische & Aquarien",
    "es": "Peces & Acuarios",
    "tr": "Balıklar & Akvaryumlar",
    "ru": "Рыбы & Аквариумы",
    "fa": "ماهی و آکواریوم"
  },
  "sub_pets_other_pets": {
    "ar": "حيوانات أخرى",
    "en": "Other Pets",
    "fr": "Autres Animaux",
    "de": "Andere Haustiere",
    "es": "Otras Mascotas",
    "tr": "Diğer Hayvanlar",
    "ru": "Другие животные",
    "fa": "سایر حیوانات"
  },
  "sub_pets_pet_accessories": {
    "ar": "مستلزمات حيوانات",
    "en": "Pet Accessories",
    "fr": "Accessoires Animaux",
    "de": "Tieraccessoires",
    "es": "Accesorios para Mascotas",
    "tr": "Evcil Hayvan Aksesuarları",
    "ru": "Товары для животных",
    "fa": "لوازم حیوانات"
  },
  "sub_sports_gym_fitness": {
    "ar": "جيم ولياقة",
    "en": "Gym & Fitness",
    "fr": "Salle de Sport & Fitness",
    "de": "Fitness & Gym",
    "es": "Gimnasio & Fitness",
    "tr": "Spor Salonu & Fitness",
    "ru": "Фитнес & Спортзал",
    "fa": "باشگاه و تناسب اندام"
  },
  "sub_sports_team_sports": {
    "ar": "كرة قدم ورياضات جماعية",
    "en": "Team Sports",
    "fr": "Sports Collectifs",
    "de": "Mannschaftssport",
    "es": "Deportes de Equipo",
    "tr": "Takım Sporları",
    "ru": "Командные виды спорта",
    "fa": "ورزش‌های تیمی"
  },
  "sub_sports_outdoor_sports": {
    "ar": "رياضات خارجية",
    "en": "Outdoor Sports",
    "fr": "Sports de Plein Air",
    "de": "Outdoor-Sport",
    "es": "Deportes al Aire Libre",
    "tr": "Açık Hava Sporları",
    "ru": "Виды спорта на открытом воздухе",
    "fa": "ورزش‌های بیرونی"
  },
  "sub_sports_fishing": {
    "ar": "صيد وأدواته",
    "en": "Fishing",
    "fr": "Pêche",
    "de": "Angeln",
    "es": "Pesca",
    "tr": "Balıkçılık",
    "ru": "Рыбалка",
    "fa": "ماهیگیری"
  },
  "sub_sports_cycling": {
    "ar": "دراجات وسكوتر",
    "en": "Cycling & Scooters",
    "fr": "Vélos & Scooters",
    "de": "Fahrräder & Roller",
    "es": "Bicicletas & Patinetes",
    "tr": "Bisiklet & Scooter",
    "ru": "Велосипеды & Скутеры",
    "fa": "دوچرخه و اسکوتر"
  },
  "sub_sports_water_sports": {
    "ar": "رياضات مائية",
    "en": "Water Sports",
    "fr": "Sports Nautiques",
    "de": "Wassersport",
    "es": "Deportes Acuáticos",
    "tr": "Su Sporları",
    "ru": "Водные виды спорта",
    "fa": "ورزش‌های آبی"
  },
  "sub_sports_sports_clothing": {
    "ar": "ملابس رياضية",
    "en": "Sports Clothing",
    "fr": "Vêtements de Sport",
    "de": "Sportkleidung",
    "es": "Ropa Deportiva",
    "tr": "Spor Giyim",
    "ru": "Спортивная одежда",
    "fa": "لباس ورزشی"
  },
  "sub_kids_toys": {
    "ar": "ألعاب أطفال",
    "en": "Toys",
    "fr": "Jouets",
    "de": "Spielzeug",
    "es": "Juguetes",
    "tr": "Oyuncaklar",
    "ru": "Игрушки",
    "fa": "اسباب‌بازی"
  },
  "sub_kids_baby_gear": {
    "ar": "مستلزمات رضع",
    "en": "Baby Gear",
    "fr": "Équipement Bébé",
    "de": "Babyausstattung",
    "es": "Artículos de Bebé",
    "tr": "Bebek Gereçleri",
    "ru": "Товары для малышей",
    "fa": "وسایل نوزاد"
  },
  "sub_kids_kids_furniture": {
    "ar": "أثاث أطفال",
    "en": "Kids Furniture",
    "fr": "Meubles Enfants",
    "de": "Kindermöbel",
    "es": "Muebles Infantiles",
    "tr": "Çocuk Mobilyaları",
    "ru": "Детская мебель",
    "fa": "مبل کودک"
  },
  "sub_hobbies_books": {
    "ar": "كتب ومجلات",
    "en": "Books & Magazines",
    "fr": "Livres & Magazines",
    "de": "Bücher & Zeitschriften",
    "es": "Libros & Revistas",
    "tr": "Kitaplar & Dergiler",
    "ru": "Книги & Журналы",
    "fa": "کتاب و مجله"
  },
  "sub_hobbies_music_instruments": {
    "ar": "آلات موسيقية",
    "en": "Musical Instruments",
    "fr": "Instruments de Musique",
    "de": "Musikinstrumente",
    "es": "Instrumentos Musicales",
    "tr": "Müzik Aletleri",
    "ru": "Музыкальные инструменты",
    "fa": "ساز موسیقی"
  },
  "sub_hobbies_photography": {
    "ar": "تصوير وإضاءة",
    "en": "Photography",
    "fr": "Photographie",
    "de": "Fotografie",
    "es": "Fotografía",
    "tr": "Fotoğrafçılık",
    "ru": "Фотография",
    "fa": "عکاسی"
  },
  "sub_hobbies_art_craft": {
    "ar": "فنون وحرف",
    "en": "Arts & Crafts",
    "fr": "Arts & Artisanat",
    "de": "Kunst & Handwerk",
    "es": "Arte & Manualidades",
    "tr": "Sanat & El Sanatları",
    "ru": "Искусство & Рукоделие",
    "fa": "هنر و صنایع دستی"
  },
  "sub_hobbies_collectibles": {
    "ar": "تحف وأنتيكات",
    "en": "Collectibles & Antiques",
    "fr": "Antiquités & Collections",
    "de": "Antiquitäten & Sammlerstücke",
    "es": "Antigüedades & Coleccionables",
    "tr": "Antikalar & Koleksiyonlar",
    "ru": "Антиквариат & Коллекционирование",
    "fa": "عتیقه‌جات و کلکسیون"
  },
  "sub_agriculture_livestock": {
    "ar": "مواشي وأبقار",
    "en": "Livestock & Cattle",
    "fr": "Bétail & Bovins",
    "de": "Vieh & Rinder",
    "es": "Ganado & Bovinos",
    "tr": "Hayvancılık & Sığırlar",
    "ru": "Скот & Крупный рогатый скот",
    "fa": "دام و گاو"
  },
  "sub_agriculture_poultry": {
    "ar": "دواجن وطيور مزرعة",
    "en": "Poultry",
    "fr": "Volaille",
    "de": "Geflügel",
    "es": "Aves de Corral",
    "tr": "Kümes Hayvanları",
    "ru": "Домашняя птица",
    "fa": "طیور مزرعه"
  },
  "sub_agriculture_agriculture_equipment": {
    "ar": "معدات زراعية",
    "en": "Agriculture Equipment",
    "fr": "Équipements Agricoles",
    "de": "Landwirtschaftliche Geräte",
    "es": "Equipos Agrícolas",
    "tr": "Tarım Ekipmanları",
    "ru": "Сельскохозяйственное оборудование",
    "fa": "ماشین‌آلات کشاورزی"
  },
  "sub_agriculture_crops_plants": {
    "ar": "محاصيل ونباتات",
    "en": "Crops & Plants",
    "fr": "Cultures & Plantes",
    "de": "Pflanzen & Kulturpflanzen",
    "es": "Cultivos & Plantas",
    "tr": "Ürünler & Bitkiler",
    "ru": "Культуры & Растения",
    "fa": "محصولات و گیاهان"
  },
  "sub_food_homemade_food": {
    "ar": "أكل بيتي وحلويات",
    "en": "Homemade Food & Sweets",
    "fr": "Cuisine Maison & Pâtisseries",
    "de": "Hausgemachtes Essen & Süßigkeiten",
    "es": "Comida Casera & Dulces",
    "tr": "Ev Yemekleri & Tatlılar",
    "ru": "Домашняя еда & Сладости",
    "fa": "غذای خانگی و شیرینی"
  },
  "sub_food_restaurant_supplies": {
    "ar": "مستلزمات مطاعم",
    "en": "Restaurant Supplies",
    "fr": "Fournitures de Restaurant",
    "de": "Restaurantbedarf",
    "es": "Suministros para Restaurantes",
    "tr": "Restoran Malzemeleri",
    "ru": "Ресторанные принадлежности",
    "fa": "تجهیزات رستوران"
  },
  "sub_food_food_products": {
    "ar": "منتجات غذائية",
    "en": "Food Products",
    "fr": "Produits Alimentaires",
    "de": "Lebensmittelprodukte",
    "es": "Productos Alimentarios",
    "tr": "Gıda Ürünleri",
    "ru": "Продукты питания",
    "fa": "محصولات غذایی"
  },
  "sub_tools_power_tools": {
    "ar": "أدوات كهربائية",
    "en": "Power Tools",
    "fr": "Outils Électriques",
    "de": "Elektrowerkzeuge",
    "es": "Herramientas Eléctricas",
    "tr": "Elektrikli Aletler",
    "ru": "Электроинструменты",
    "fa": "ابزار برقی"
  },
  "sub_tools_hand_tools": {
    "ar": "أدوات يدوية",
    "en": "Hand Tools",
    "fr": "Outils Manuels",
    "de": "Handwerkzeuge",
    "es": "Herramientas Manuales",
    "tr": "El Aletleri",
    "ru": "Ручные инструменты",
    "fa": "ابزار دستی"
  },
  "sub_tools_industrial": {
    "ar": "معدات صناعية",
    "en": "Industrial Equipment",
    "fr": "Équipements Industriels",
    "de": "Industrieanlagen",
    "es": "Equipos Industriales",
    "tr": "Endüstriyel Ekipmanlar",
    "ru": "Промышленное оборудование",
    "fa": "تجهیزات صنعتی"
  },
  "sub_tools_generators": {
    "ar": "مولدات وطاقة",
    "en": "Generators & Energy",
    "fr": "Générateurs & Énergie",
    "de": "Generatoren & Energie",
    "es": "Generadores & Energía",
    "tr": "Jeneratörler & Enerji",
    "ru": "Генераторы & Энергия",
    "fa": "ژنراتور و انرژی"
  },
  "sub_general_other": {
    "ar": "أخرى",
    "en": "Other",
    "fr": "Autre",
    "de": "Sonstiges",
    "es": "Otro",
    "tr": "Diğer",
    "ru": "Другое",
    "fa": "سایر"
  }
};

/**
 * Get category name in a specific language
 * @param {string} categoryId - e.g. 'sports'
 * @param {string} lang - e.g. 'fr'
 * @returns {string} translated name
 */
function getCategoryName(categoryId, lang = 'ar') {
  const key = `cat_${categoryId}`;
  const t = CATEGORY_TRANSLATIONS[key];
  return t?.[lang] || t?.en || t?.ar || categoryId;
}

function getSubcategoryName(categoryId, subcategoryId, lang = 'ar') {
  const key = `sub_${categoryId}_${subcategoryId}`;
  const t = CATEGORY_TRANSLATIONS[key];
  return t?.[lang] || t?.en || t?.ar || subcategoryId;
}

export { CATEGORY_TRANSLATIONS, getCategoryName, getSubcategoryName };
