version: "3"
services:
  krakend:
    image: devopsfaith/krakend:latest
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "${KRAKEND_PORT:-8080}:8080"
    depends_on:
      - fake_api
    env_file:
      - .env

  fake_api:
    build: .
    ports:
      - "${FAKE_API_PORT:-8000}:8000"
    environment:
      - PORT=8000
