[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install --legacy-peer-deps"

[deploy]
startCommand = "cd backend && node server/index.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
sleepApplication = false
