#!/usr/bin/env node
// AUTO-GENERATED script — run to regenerate category translations
// Usage: node backend/scripts/generateCategoryTranslations.js
// Or call: POST /api/ads/admin/regenerate-translations (x-admin-key: xtox-admin-2026)

import { CATEGORIES } from '../config/categories.js';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GROQ_KEY = process.env.GROQ_API_KEY; // Set GROQ_API_KEY env var before running
const LANGS = ['fr', 'de', 'es', 'tr', 'ru', 'fa'];
const LANG_NAMES = { fr: 'French', de: 'German', es: 'Spanish', tr: 'Turkish', ru: 'Russian', fa: 'Persian/Farsi' };

async function translateBatch(items) {
  // items = [{id, ar, en}, ...]
  const prompt = `Translate these marketplace category names into ${LANGS.map(l => LANG_NAMES[l]).join(', ')}.
Return ONLY valid JSON object with key "translations" containing an array where each object has: id, ${LANGS.join(', ')}
Keep translations SHORT and marketplace-appropriate (1-4 words).
Items to translate:
${JSON.stringify(items, null, 2)}`;

  const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${GROQ_KEY}` },
    body: JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 4000,
      temperature: 0.2,
      response_format: { type: 'json_object' }
    })
  });
  if (!res.ok) throw new Error(`Groq ${res.status}: ${await res.text()}`);
  const data = await res.json();
  const content = data.choices[0].message.content;
  // Parse — Groq may return {translations: [...]} or [...] directly
  const parsed = JSON.parse(content);
  return Array.isArray(parsed) ? parsed : (parsed.translations || parsed.items || Object.values(parsed)[0]);
}

async function main() {
  const translations = {};

  for (const cat of CATEGORIES) {
    console.log(`Translating category: ${cat.id} (${cat.nameEn})...`);
    // Build items array for this batch
    const catItem = { id: `cat_${cat.id}`, ar: cat.name, en: cat.nameEn };
    const subItems = cat.subcategories.map(s => ({ id: `sub_${cat.id}_${s.id}`, ar: s.name, en: s.nameEn }));
    const allItems = [catItem, ...subItems];

    try {
      const result = await translateBatch(allItems);
      for (const r of result) {
        const original = allItems.find(i => i.id === r.id);
        if (original) {
          translations[r.id] = { ar: original.ar, en: original.en, ...r };
          delete translations[r.id].id;
        }
      }
      await new Promise(r => setTimeout(r, 500)); // avoid rate limit
    } catch (err) {
      console.error(`Failed to translate ${cat.id}:`, err.message);
      // Fallback: use Arabic + English as-is
      for (const item of allItems) {
        translations[item.id] = { ar: item.ar, en: item.en };
      }
    }
  }

  const output = `// AUTO-GENERATED by scripts/generateCategoryTranslations.js
// Languages: ar, en, fr, de, es, tr, ru, fa
// Regenerate: node backend/scripts/generateCategoryTranslations.js
// Or POST /api/ads/admin/regenerate-translations with x-admin-key header

const CATEGORY_TRANSLATIONS = ${JSON.stringify(translations, null, 2)};

/**
 * Get category name in a specific language
 * @param {string} categoryId - e.g. 'sports'
 * @param {string} lang - e.g. 'fr'
 * @returns {string} translated name
 */
function getCategoryName(categoryId, lang = 'ar') {
  const key = \`cat_\${categoryId}\`;
  const t = CATEGORY_TRANSLATIONS[key];
  return t?.[lang] || t?.en || t?.ar || categoryId;
}

function getSubcategoryName(categoryId, subcategoryId, lang = 'ar') {
  const key = \`sub_\${categoryId}_\${subcategoryId}\`;
  const t = CATEGORY_TRANSLATIONS[key];
  return t?.[lang] || t?.en || t?.ar || subcategoryId;
}

export { CATEGORY_TRANSLATIONS, getCategoryName, getSubcategoryName };
`;

  writeFileSync(join(__dirname, '../config/categoryTranslations.js'), output, 'utf8');
  console.log('✅ Translations written to backend/config/categoryTranslations.js');
  console.log(`Total entries: ${Object.keys(translations).length}`);
}

main().catch(console.error);
